
export const competencyLabels = {
  controlsAccelerator : 'Accelerator',
  controlsClutch: 'Clutch',
  controlsGears: 'Gears',
  controlsFootbrake: 'Footbrake',
  controlsParkingBrake: 'Parking brake',
  controlsSteering: 'Steering',
  precautions: 'Precautions',
  ancillaryControls: 'Ancillary Controls',
  moveOffSafety: 'Safety',
  moveOffControl: 'Control',
  useOfMirrorsSignalling:'Signalling',
  useOfMirrorsChangeDirection:'Change direction',
  useOfMirrorsChangeSpeed: 'Change speed',
  signalsNecessary: 'Necessary',
  signalsCorrectly: 'Correctly',
  signalsTimed: 'Timed',
  junctionsApproachSpeed: 'Approach speed',
  junctionsObservation: 'Observation',
  junctionsTurningRight: 'Turning right',
  junctionsTurningLeft:'Turning left',
  junctionsCuttingCorners: 'Cutting corners',
  judgementOvertaking: 'Overtaking',
  judgementMeeting: 'Meeting',
  judgementCrossing: 'Crossing',
  positioningNormalDriving: 'Normal driving',
  positioningLaneDiscipline: 'Lane Discipline',
  clearance: 'Clearance',
  followingDistance: 'Following distance',
  useOfSpeed: 'Use of speed',
  progressAppropriateSpeed: 'Appropriate speed',
  progressUndueHesitation: 'Undue hesitation',
  responseToSignsTrafficSigns: 'Traffic signs',
  responseToSignsRoadMarkings: 'Road markings',
  responseToSignsTrafficLights: 'Traffic lights',
  responseToSignsTrafficControllers: 'Traffic controllers',
  responseToSignsOtherRoadUsers: 'Other road users',
  pedestrianCrossings: 'Pedestrian crossings',
  positionNormalStops: 'Position/normal stop',
  awarenessPlanning: 'Awareness planning',
};
