/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON Schema definition for Examiner Work Schedule
 */
export interface ExaminerWorkSchedule {
  /**
   * The examiner details
   */
  examiner?: {
    /**
     * The examiner's DSA staff number
     */
    staffNumber?: string;
    examinerName?: Name;
    permTestCentre?: TestCentre;
    [k: string]: any;
  };
  /**
   * A test slot, possibly populated with booking data
   */
  testSlot?: any[];
  /**
   * An examiner's personal commitment
   */
  personalCommitment?: any[];
  /**
   * An examiner's non test activity (associated with a test slot duration)
   */
  nonTestActivity?: any[];
  /**
   * Advance details of a test slot
   */
  advanceTestSlot?: any[];
  /**
   * Temporary secondment of the examiner to an alternative test centre
   */
  deployment?: any[];
  [k: string]: any;
}
/**
 * Details of the individual's name
 */
export interface Name {
  /**
   * The individual's title
   */
  title: string;
  /**
   * The individual's forename
   */
  firstName: string;
  /**
   * The individual's second name
   */
  secondName?: string;
  /**
   * The individual's third name
   */
  thirdName?: string;
  /**
   * The individual's surname
   */
  lastName: string;
  [k: string]: any;
}
/**
 * Details of the test centre
 */
export interface TestCentre {
  /**
   * Identifier for the test centre
   */
  centreId?: number;
  /**
   * Name of the test centre
   */
  centreName?: string;
  /**
   * Cost centre code for the test centre
   */
  costCode?: string;
  [k: string]: any;
}
