import { OutcomeBehaviourMapping } from '../../providers/outcome-behaviour-map/outcome-behaviour-map.model';

export const behaviourMap: OutcomeBehaviourMapping = {
  ['1']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'A' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'A' },
    ['eco']: { display: 'A' },
    ['circuit']: { display: 'Y' },
  },
  ['2']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'A' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'A' },
    ['eco']: { display: 'A' },
    ['circuit']: { display: 'Y' },
  },
  ['3']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y', defaultValue: 'Yes' },
    ['eta']: { display: 'A' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'A' },
    ['eco']: { display: 'A' },
    ['circuit']: { display: 'Y' },
  },
  ['4']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'A' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'A' },
    ['eco']: { display: 'A' },
    ['circuit']: { display: 'Y' },
  },
  ['5']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'A' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'A' },
    ['eco']: { display: 'A' },
    ['circuit']: { display: 'Y' },
  },
  ['11']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['20']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['21']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['22']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['23']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['24']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['25']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['26']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['27']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['28']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['32']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['33']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['34']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['35']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['36']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['37']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['38']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['40']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['41']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['84']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['51']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['52']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['55']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['58']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['59']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['60']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['61']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['62']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['63']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['64']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['66']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['67']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['68']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['69']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['70']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['71']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['73']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['74']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'N' },
    ['debriefWitnessed']: { display: 'N' },
    ['identification']: { display: 'N' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
  ['75']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'Y' },
    ['d255']: { display: 'Y' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'Y' },
  },
  ['82']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
  },
  ['83']: {
    ['routeNumber']: { display: 'N' },
    ['candidateDescription']: { display: 'Y' },
    ['debriefWitnessed']: { display: 'Y' },
    ['identification']: { display: 'Y' },
    ['weatherConditions']: { display: 'N' },
    ['d255']: { display: 'N' },
    ['eta']: { display: 'N' },
    ['additionalInformation']: { display: 'Y' },
    ['faultComment']: { display: 'N' },
    ['circuit']: { display: 'N' },
  },
};
