# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Signs and builds the app with the DVSA production distribution certificate & provisioning profile"
  lane :build do
   upgrade_super_old_xcode_project(
    path: "platforms/ios/mes-mobile-app.xcodeproj",
    team_id: "K84TL26V3P"
  )
  disable_automatic_code_signing(path: "platforms/ios/mes-mobile-app.xcodeproj")
  # Make sure the XCode project is using the VOSA/DVSA team
  update_project_team(
   path: "platforms/ios/mes-mobile-app.xcodeproj",
   teamid: "K84TL26V3P")

   # Update the project's provisoning settings to use our distribution cert
   update_project_provisioning(
    xcodeproj: "platforms/ios/mes-mobile-app.xcodeproj",
    profile: "/Users/mes/certs/Mobile_Examiner.mobileprovision", 
    target_filter: ".*mes-mobile-app.*", # matches name or type of a target, see https://medium.com/@andersongusmao/xcode-targets-with-multiples-build-configuration-90a575ddc687 for an explanation 
    build_configuration: "Release",
    code_signing_identity: "iPhone Distribution: Vehicle and Operator Services Agency"
  )
   

   build_ios_app(
    export_options: {
      provisioningProfiles: {
        "uk.gov.dvsa.mobile-examiner" => "Mobile Examiner",
      }
    },
    project:  "platforms/ios/mes-mobile-app.xcodeproj",
        scheme: "mes-mobile-app",
        configuration: "Release",
        output_directory: "build",
        silent: false,
        output_name: "mes-mobile-app.ipa",
        export_method: "enterprise",
        codesigning_identity: "iPhone Distribution: Vehicle and Operator Services Agency"

   )
  end
end