export enum TestCategory {
  A = 'A',
  A1 = 'A1',
  A2 = 'A2',
  ADI2 = 'ADI2',
  ADI3 = 'ADI3',
  AM = 'AM',
  B = 'B',
  B1 = 'B1',
  BE = 'B+E',
  C = 'C',
  C1 = 'C1',
  C1E = 'C1+E',
  CCPC = 'CCPC',
  CE = 'C+E',
  D = 'D',
  D1 = 'D1',
  D1E = 'D1+E',
  DCPC = 'DCPC',
  DE =  'D+E',
  EUA1M1 = 'EUA1M1',
  EUA1M2 = 'EUA1M2',
  EUA2M1 = 'EUA2M1',
  EUA2M2 = 'EUA2M2',
  EUAM1 = 'EUAM1',
  EUAM2 = 'EUAM2',
  EUAMM1 = 'EUAMM1',
  EUAMM2 = 'EUAMM2',
  F = 'F',
  G = 'G',
  H = 'H',
  K = 'K',
  SC = 'SC',
}

export const testCategoryIcons = {
  [TestCategory.A]: 'assets/icon/test-categories/A.png',
  [TestCategory.A1]: 'assets/icon/test-categories/A1.png',
  [TestCategory.A2]: 'assets/icon/test-categories/A2.png',
  [TestCategory.ADI2]: '',
  [TestCategory.ADI3]: '',
  [TestCategory.AM]: 'assets/icon/test-categories/AM.png',
  [TestCategory.B]: 'assets/icon/test-categories/B.png',
  [TestCategory.B1]: 'assets/icon/test-categories/B1.png',
  [TestCategory.BE]: 'assets/icon/test-categories/BE.png',
  [TestCategory.C]: 'assets/icon/test-categories/C.png',
  [TestCategory.C1]: 'assets/icon/test-categories/C1.png',
  [TestCategory.C1E]: 'assets/icon/test-categories/C1E.png',
  [TestCategory.CCPC]: '',
  [TestCategory.CE]: 'assets/icon/test-categories/CE.png',
  [TestCategory.D]: 'assets/icon/test-categories/D.png',
  [TestCategory.D1]: 'assets/icon/test-categories/D1.png',
  [TestCategory.D1E]: 'assets/icon/test-categories/D1E.png',
  [TestCategory.DCPC]: '',
  [TestCategory.DE]: 'assets/icon/test-categories/DE.png',
  [TestCategory.EUA1M1]: '',
  [TestCategory.EUA1M2]: '',
  [TestCategory.EUA2M1]: '',
  [TestCategory.EUA2M2]: '',
  [TestCategory.EUAM1]: '',
  [TestCategory.EUAM2]: '',
  [TestCategory.EUAMM1]: '',
  [TestCategory.EUAMM2]: '',
  [TestCategory.F]: '',
  [TestCategory.G]: '',
  [TestCategory.H]: '',
  [TestCategory.K]: '',
  [TestCategory.SC]: '',
};
